# Generated by Django 4.2.1 on 2023-05-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ultimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_Name', models.CharField(max_length=25)),
                ('Vendor_Code', models.IntegerField()),
                ('Vendor_Address', models.CharField(max_length=25)),
                ('GSTIN_Number', models.IntegerField()),
                ('Contact_Number', models.IntegerField()),
                ('Vendor_Email_ID', models.EmailField(max_length=254)),
            ],
        ),
    ]
