# Generated by Django 4.2.1 on 2023-05-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimate',
            name='GSTIN_Number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ultimate',
            name='Vendor_Code',
            field=models.CharField(max_length=25),
        ),
    ]
