# Generated by Django 4.2.1 on 2023-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ultimate_gstin_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimate',
            name='Contact_Number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ultimate',
            name='GSTIN_Number',
            field=models.CharField(max_length=15),
        ),
    ]
